# Generated by Django 5.2.5 on 2025-09-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proyecto o producto', max_length=200, verbose_name='Producto/Solución')),
                ('fase', models.CharField(choices=[('ejecucion', 'Ejecución'), ('completado', 'Completado'), ('pausado', 'Pausado')], default='ejecucion', help_text='Fase actual del proyecto', max_length=20, verbose_name='Fase')),
                ('objetivo', models.TextField(help_text='Descripción detallada del objetivo del proyecto', verbose_name='Objetivo')),
                ('status', models.CharField(choices=[('en_curso', 'EN CURSO'), ('en_seguimiento', 'EN SEGUIMIENTO'), ('pausado', 'PAUSADO')], default='en_curso', help_text='Estado actual del proyecto', max_length=20, verbose_name='Status')),
                ('prioridad', models.CharField(choices=[('normal', 'NORMAL'), ('alta', 'ALTA'), ('baja', 'BAJA')], default='normal', help_text='Nivel de prioridad del proyecto', max_length=10, verbose_name='Prioridad')),
                ('ultima_actualizacion', models.TextField(help_text='Descripción de la última actualización del proyecto', verbose_name='Última actualización')),
                ('listo_para_ofrecer', models.CharField(choices=[('si', 'SI'), ('no', 'NO')], default='no', help_text='Indica si el proyecto está listo para ser ofrecido', max_length=5, verbose_name='¿Listo para ofrecer?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['nombre'],
            },
        ),
    ]
