# Configuración optimizada para uv con Django en Nixpacks
[variables]
NIXPACKS_PYTHON_PACKAGE_MANAGER = "uv"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
nixPkgs = ['python311', 'uv', 'postgresql']

[phases.install]
cmds = [
  'uv sync --frozen --no-dev'
]

[phases.build]  
cmds = [
  'mkdir -p static',
  'uv run python manage.py collectstatic --noinput'
]
