# Configuración optimizada para uv con Django en Nixpacks
[variables]
NIXPACKS_PYTHON_PACKAGE_MANAGER = "uv"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
nixPkgs = ['python311', 'uv', 'libpq']

[phases.install]
cmds = [
  'uv sync --frozen --no-dev'
]

[phases.build]  
cmds = [
  'mkdir -p static',
  'uv run python manage.py collectstatic --noinput'
]

[start]
cmd = 'uv run python manage.py migrate && uv run gunicorn core.wsgi:application --bind 0.0.0.0:8080 --workers 3 --timeout 120'
