# Generated by Django 5.2.5 on 2025-09-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección completa del usuario', max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.CharField(blank=True, help_text='Número de cédula, pasaporte o RIF', max_length=20, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('V', 'Cédula de Identidad Venezolana'), ('E', 'Cédula de Extranjero'), ('P', 'Pasaporte'), ('J', 'RIF Jurídico'), ('G', 'RIF Gubernamental')], help_text='Tipo de documento de identificación', max_length=1, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False), ('tipo_documento__isnull', False)), fields=('tipo_documento', 'documento'), name='unique_documento_per_tipo'),
        ),
    ]
