# Generated by Django 5.2.5 on 2025-09-08 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('test', 'Prueba'), ('user', 'Usuario Específico'), ('broadcast', 'Broadcast'), ('admin', 'Administrador')], max_length=20, verbose_name='Tipo')),
                ('devices_count', models.PositiveIntegerField(default=0, verbose_name='Dispositivos alcanzados')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('data_payload', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('target_user', models.ForeignKey(blank=True, help_text='Dejar vacío para broadcast', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destino')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
